
spring:
  application:
    name: dataset-graph-fetcher
  cloud:
    stream:
      bindings:
        input:
          destination: dataset-url
        output:
          destination: dataset-graph

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/},${EUREKA_URL:http://localhost:8762/eureka/}

info:
  crawler:
    tripleStore:
      url: ${CRAWLER_TRIPLESTORE_URL}/%s/query
      username: ${CRAWLER_TRIPLESTORE_USERNAME}
      password: ${CRAWLER_TRIPLESTORE_PASSWORD}

logging:
  level:
    org:
      apache:
        jena: error