version: '3.2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      timeout: 5s
      interval: 3s
      retries: 30
      test: ["CMD", "rabbitmqctl", "status"]
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/
  es:
    image: elasticsearch:7.3.2
    ports:
      - 9200:9200
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - eslog:/var/log/elasticsearch/
    environment:
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - discovery.type=single-node
      - bootstrap.memory_lock=true
#      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.3.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
  logstash:
    image: logstash:7.3.2
    volumes:
      - ./logstash_AMQP.conf:/config-dir/logstash.conf
    ports:
      - 5000:5000
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - rabbitmq
      - es
  mysql:
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=opal
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 30
  discovery-server:
    image: mnafshin/opal-discovery-server:latest
    ports:
      - 8761:8761
  dataset-fetcher:
    image: mnafshin/opal-dataset-fetcher:latest
    ports:
      - 8001:8001
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - CRAWLER_TRIPLESTORE_URL=${CRAWLER_TRIPLESTORE_URL}
      - CRAWLER_TRIPLESTORE_USERNAME=${CRAWLER_TRIPLESTORE_USERNAME}
      - CRAWLER_TRIPLESTORE_PASSWORD=${CRAWLER_TRIPLESTORE_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - DATABASE_URL=mysql
      - DATABASE_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - mysql
  opal-confirm-conversion-service:
    image: mnafshin/opal-confirm-conversion-service
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - dataset-fetcher
  quality-metrics-service:
    image: mnafshin/opal-quality-metrics-service:latest
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - dataset-fetcher
      - opal-confirm-conversion-service
  quality-metrics-service_replica_1:
    image: mnafshin/opal-quality-metrics-service:latest
    volumes:
      - logvolume2:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - dataset-fetcher
      - opal-confirm-conversion-service
  quality-metrics-service_replica_2:
    image: mnafshin/opal-quality-metrics-service:latest
    volumes:
      - logvolume3:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - dataset-fetcher
      - opal-confirm-conversion-service
  triplestore-writer:
    image: mnafshin/opal-triplestore-writer:latest
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - OPAL_TRIPLESTORE_URL=${OPAL_TRIPLESTORE_URL}
      - OPAL_TRIPLESTORE_USERNAME=${OPAL_TRIPLESTORE_USERNAME}
      - OPAL_TRIPLESTORE_PASSWORD=${OPAL_TRIPLESTORE_PASSWORD}
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - dataset-fetcher
      - opal-confirm-conversion-service
      - quality-metrics-service
  elasticsearch-writer:
    image: mnafshin/opal-elasticsearch-writer:latest
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - dataset-fetcher
      - opal-confirm-conversion-service
      - quality-metrics-service
  webservices:
    image: mnafshin/opal-webservices:latest
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - OPAL_TRIPLESTORE_URL=fuseki
      - OPAL_TRIPLESTORE_USERNAME=${OPAL_TRIPLESTORE_USERNAME}
      - OPAL_TRIPLESTORE_PASSWORD=${OPAL_TRIPLESTORE_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - dataset-fetcher
      - opal-confirm-conversion-service
      - quality-metrics-service
volumes:
  rabbitmqdata:
  esdata01:
  eslog:
  mysqldata:
  logvolume1:
  logvolume2:
  logvolume3: