version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3.7.23-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      timeout: 5s
      interval: 3s
      retries: 30
      test: ["CMD", "rabbitmqctl", "status"]
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/
  es:
    image: elasticsearch:7.3.2
    ports:
      - 9200:9200
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - eslog:/var/log/elasticsearch/
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.3.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
  logstash:
    image: logstash:7.3.2
    volumes:
      - ./logstash_AMQP.conf:/config-dir/logstash.conf
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - XPACK_MONITORING_ENABLED=false
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=""
    ports:
      - 5000:5000
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - rabbitmq
      - es
  mysql:
    image: mysql:8.0.17
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=opal
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 30
  discovery-server:
    build: discovery-server
    ports:
      - 8761:8761
  config-server:
    build: config-server
    ports:
      - 8888:8888
    environment:
      - CONFIG_REPO=https://github.com/projekt-opal/converter-configuration.git
      - CONFIG_REPO_DEFAULT_BRANCH=master
      - EUREKA_URL=http://discovery-server:8761/eureka/
  dataset-fetcher:
    build: dataset-fetcher
    ports:
      - 8001:8001
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - CRAWLER_TRIPLESTORE_URL=${CRAWLER_TRIPLESTORE_URL}
      - CRAWLER_TRIPLESTORE_USERNAME=${CRAWLER_TRIPLESTORE_USERNAME}
      - CRAWLER_TRIPLESTORE_PASSWORD=${CRAWLER_TRIPLESTORE_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - DATABASE_URL=mysql
      - DATABASE_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - config-server
      - mysql
  opal-confirm-conversion-service:
    build: opal-confirm-conversion-service
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - config-server
      - dataset-fetcher
  quality-metrics-service:
    build: quality-metrics-service
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - config-server
      - dataset-fetcher
      - opal-confirm-conversion-service
  quality-metrics-service_replica_1:
    build: quality-metrics-service
    volumes:
      - logvolume2:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - config-server
      - dataset-fetcher
      - opal-confirm-conversion-service
  quality-metrics-service_replica_2:
    build: quality-metrics-service
    volumes:
      - logvolume3:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - config-server
      - dataset-fetcher
      - opal-confirm-conversion-service
  triplestore-writer:
    build: triplestore-writer
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - OPAL_TRIPLESTORE_URL=${OPAL_TRIPLESTORE_URL}
      - OPAL_TRIPLESTORE_USERNAME=${OPAL_TRIPLESTORE_USERNAME}
      - OPAL_TRIPLESTORE_PASSWORD=${OPAL_TRIPLESTORE_PASSWORD}
      - MIN_CONCURRENCY_WRITER=3
      - MAX_CONCURRENCY_WRITER=3
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - config-server
      - dataset-fetcher
      - opal-confirm-conversion-service
      - quality-metrics-service
  elasticsearch-writer:
    build: elasticsearch-writer
    volumes:
      - logvolume1:/var/log/converter/
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - OPAL_ELASTICSEARCH_URL=opaldata.cs.upb.de
      - OPAL_ELASTICSEARCH_PORT=9200
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - config-server
      - dataset-fetcher
      - opal-confirm-conversion-service
      - quality-metrics-service
volumes:
  rabbitmqdata:
  esdata01:
  eslog:
  mysqldata:
  logvolume1:
  logvolume2:
  logvolume3: