version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3.7.23-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      timeout: 5s
      interval: 3s
      retries: 30
      test: ["CMD", "rabbitmqctl", "status"]
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/
  es:
    image: elasticsearch:7.3.2
    ports:
      - 9200:9200
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - eslog:/var/log/elasticsearch/
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.3.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
  logstash:
    image: logstash:7.3.2
    volumes:
      - ./logstash_AMQP.conf:/config-dir/logstash.conf
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - XPACK_MONITORING_ENABLED=false
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=""
    ports:
      - 5000
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - rabbitmq
      - es
  discovery-server:
    build: discovery-server
    ports:
      - 8761:8761
  config-server:
    build: config-server
    ports:
      - 8888:8888
    environment:
      - CONFIG_REPO=https://github.com/projekt-opal/converter-configuration.git
      - CONFIG_REPO_DEFAULT_BRANCH=master
      - EUREKA_URL=http://discovery-server:8761/eureka/
  dataset-fetcher:
    build: dataset-fetcher
    ports:
      - 8001:8001
    volumes:
      - h2data:/db
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - CRAWLER_TRIPLESTORE_URL=${CRAWLER_TRIPLESTORE_URL}
      - CRAWLER_TRIPLESTORE_USERNAME=${CRAWLER_TRIPLESTORE_USERNAME}
      - CRAWLER_TRIPLESTORE_PASSWORD=${CRAWLER_TRIPLESTORE_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - H2_DB_PASSWORD=${H2_DB_PASSWORD}
      - H2_DB_PATH=/db
    depends_on:
      - rabbitmq
      - discovery-server
      - config-server
  dataset-file-fetcher:
    build: dataset-file-fetcher
    ports:
      - 8007:8007
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - PORTAL=europeandataportal
      - FOLDER_PATH=/data
    depends_on:
      - rabbitmq
      - discovery-server
      - config-server
    volumes:
      - ${DATASET_FOLDER}:/data
  opal-confirm-conversion-service:
    build: opal-confirm-conversion-service
    ports:
      - 8002
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
    depends_on:
      - rabbitmq
      - discovery-server
      - config-server
  data-cleaner-service:
    build: data-cleaner-service
    ports:
      - 8006:8006
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
    depends_on:
      - rabbitmq
      - discovery-server
      - config-server
  quality-metrics-service:
    build: quality-metrics-service
    ports:
      - 8003
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
    depends_on:
      - rabbitmq
      - discovery-server
      - config-server
  triplestore-writer:
    build: triplestore-writer
    ports:
      - 8004
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - OPAL_TRIPLESTORE_URL=${OPAL_TRIPLESTORE_URL}
      - OPAL_TRIPLESTORE_USERNAME=${OPAL_TRIPLESTORE_USERNAME}
      - OPAL_TRIPLESTORE_PASSWORD=${OPAL_TRIPLESTORE_PASSWORD}
      - MIN_CONCURRENCY_WRITER=3
      - MAX_CONCURRENCY_WRITER=3
    depends_on:
      - rabbitmq
      - discovery-server
      - config-server
  elasticsearch-writer:
    build: elasticsearch-writer
    ports:
      - 8005
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVER_URL=http://config-server:8888
      - OPAL_ELASTICSEARCH_URL=opaldata.cs.upb.de
      - OPAL_ELASTICSEARCH_PORT=9200
    depends_on:
      - rabbitmq
      - discovery-server
      - config-server
volumes:
  rabbitmqdata:
  esdata01:
  eslog:
  h2data: