version: "2.1"

services:
  fuseki-data:
    image: busybox
    volumes:
      - /fuseki
  fuseki:
    image: stain/jena-fuseki
    ports:
      - 3030:3030
    volumes_from:
      - fuseki-data:rw
    environment:
      - ADMIN_PASSWORD=${OPAL_TRIPLESTORE_PASSWORD}
      - JVM_ARGS=-Xmx16g
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      timeout: 5s
      interval: 3s
      retries: 30
      test: ["CMD", "rabbitmqctl", "status"]
  es:
    image: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:latest
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
  logstash:
    image: logstash:latest
    volumes:
      - ./logstash_AMQP.conf:/config-dir/logstash.conf
    ports:
      - 5000:5000
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - es
      - rabbitmq
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=opal
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 30
  discovery-server:
    image: mnafshin/opal-discovery-server:latest
    ports:
      - 8761:8761
  discovery-server-replica:
    image: mnafshin/opal-discovery-server:latest
    ports:
      - 8762:8761
  dataset-fetcher:
    image: mnafshin/opal-dataset-fetcher:latest
    ports:
      - 8001:8001
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - CRAWLER_TRIPLESTORE_USERNAME=${CRAWLER_TRIPLESTORE_USERNAME}
      - CRAWLER_TRIPLESTORE_PASSWORD=${CRAWLER_TRIPLESTORE_PASSWORD}
      - CRAWLER_TRIPLESTORE_URL=${CRAWLER_TRIPLESTORE_URL}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - EUREKA_URL2=http://discovery-server-replica:8762/eureka/
      - DATABASE_URL=mysql
      - DATABASE_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - discovery-server-replica
      - es
      - mysql
  opal-confirm-conversion-service:
    image: mnafshin/opal-confirm-conversion-service
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - EUREKA_URL2=http://discovery-server-replica:8762/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - discovery-server-replica
      - es
      - fuseki
      - dataset-fetcher
  quality-metrics-service:
    image: mnafshin/opal-quality-metrics-service:latest
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - EUREKA_URL2=http://discovery-server-replica:8762/eureka/
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - discovery-server-replica
      - es
      - fuseki
      - dataset-fetcher
      - opal-confirm-conversion-service
  triplestore-writer:
    image: mnafshin/opal-triplestore-writer:latest
    environment:
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=http://discovery-server:8761/eureka/
      - EUREKA_URL2=http://discovery-server-replica:8762/eureka/
      - OPAL_TRIPLESTORE_URL=fuseki
      - OPAL_TRIPLESTORE_USERNAME=${OPAL_TRIPLESTORE_USERNAME}
      - OPAL_TRIPLESTORE_PASSWORD=${OPAL_TRIPLESTORE_PASSWORD}
    depends_on:
      - rabbitmq
      - logstash
      - discovery-server
      - discovery-server-replica
      - es
      - fuseki
      - dataset-fetcher
      - opal-confirm-conversion-service
      - quality-metrics-service