spring:
  application:
    name: dataset-url-fetcher
  cloud:
    stream:
      rabbit:
        bindings:
          output:
            destination: dataset-url

server:
  port: ${PORT:8001}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/},${EUREKA_URL:http://localhost:8762/eureka/}

info:
  crawler:
    tripleStore:
      url: ${CRAWLER_TRIPLESTORE_URL}/%s/query
      username: ${CRAWLER_TRIPLESTORE_USERNAME}
      password: ${CRAWLER_TRIPLESTORE_PASSWORD}