spring:
  application:
    name: tripleStore-writer
  cloud:
    stream:
      bindings:
        input:
          destination: quality-added-datasets
  rabbitmq:
    host: ${RABBITMQ_ADDRESS}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/},${EUREKA_URL2:http://localhost:8762/eureka/}


info:
  opal:
    tripleStore:
      url: http://${OPAL_TRIPLESTORE_URL}:3030/opal
      username: ${OPAL_TRIPLESTORE_USERNAME}
      password: ${OPAL_TRIPLESTORE_PASSWORD}

logging:
  level:
    org:
      apache:
        jena: error
    SPARQL: error