
spring:
  application:
    name: quality-metrics-service
  cloud:
    stream:
      bindings:
        input:
          destination: opal-confirmed
          group: civet
        output:
          destination: quality-added-datasets
  rabbitmq:
    host: ${RABBITMQ_ADDRESS}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/},${EUREKA_URL2:http://localhost:8762/eureka/}


logging:
  level:
    org:
      apache:
        jena: error