spring:
  application:
    name: discovery-server

server:
  port: ${PORT:8761}

client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
