spring:
  application:
    name: elasticsearch-writer
  cloud:
    stream:
      bindings:
        input:
          destination: quality-added-datasets
          group: elasticsearch
  rabbitmq:
    host: ${RABBITMQ_ADDRESS}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


#info:
#  opal:
#    elasticsearch:
#      url: http://${OPAL_ELASTICSEARCH_URL}:9200
#      username: ${OPAL_ELASTICSEARCH_USERNAME}
#      password: ${OPAL_ELASTICSEARCH_PASSWORD}
